### ISSUE TITLE
Readme has incorrect instructions for project installation and configuration

### ISSUE THREAD

**Issue by dgj796** [nusait/nuldap-laravel#4]
Readme file incorrectly instructs to install project:

```
composer require nusait/nuldap
```

Correct installation:

```
composer require nusait/nuldap-laravel
```

Readme file incorrectly instructs to add the following service provider to config/app.php:

```
Nusait\Nuldap\LdapServiceProvider::class,
```

Correct service provided to add to config/app.php:

```
Nusait\Nuldap\NuldapServiceProvider::class,
```

**Comment by azamtav** [comment]
Updated the readme 3a8c09d23c7492d6c0c8be14fb82c0dfdae57fd6
